# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AvroFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, feed_name: str=None, input_file_location: str=None):  # noqa: E501
        """AvroFile - a model defined in Swagger

        :param feed_name: The feed_name of this AvroFile.  # noqa: E501
        :type feed_name: str
        :param input_file_location: The input_file_location of this AvroFile.  # noqa: E501
        :type input_file_location: str
        """
        self.swagger_types = {
            'feed_name': str,
            'input_file_location': str
        }

        self.attribute_map = {
            'feed_name': 'feedName',
            'input_file_location': 'inputFileLocation'
        }
        self._feed_name = feed_name
        self._input_file_location = input_file_location

    @classmethod
    def from_dict(cls, dikt) -> 'AvroFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AvroFile of this AvroFile.  # noqa: E501
        :rtype: AvroFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feed_name(self) -> str:
        """Gets the feed_name of this AvroFile.


        :return: The feed_name of this AvroFile.
        :rtype: str
        """
        return self._feed_name

    @feed_name.setter
    def feed_name(self, feed_name: str):
        """Sets the feed_name of this AvroFile.


        :param feed_name: The feed_name of this AvroFile.
        :type feed_name: str
        """

        self._feed_name = feed_name

    @property
    def input_file_location(self) -> str:
        """Gets the input_file_location of this AvroFile.


        :return: The input_file_location of this AvroFile.
        :rtype: str
        """
        return self._input_file_location

    @input_file_location.setter
    def input_file_location(self, input_file_location: str):
        """Sets the input_file_location of this AvroFile.


        :param input_file_location: The input_file_location of this AvroFile.
        :type input_file_location: str
        """

        self._input_file_location = input_file_location
