# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateRule(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, feed_name: str=None, input_file_location: str=None, file_format: str=None):  # noqa: E501
        """UpdateRule - a model defined in Swagger

        :param feed_name: The feed_name of this UpdateRule.  # noqa: E501
        :type feed_name: str
        :param input_file_location: The input_file_location of this UpdateRule.  # noqa: E501
        :type input_file_location: str
        :param file_format: The file_format of this UpdateRule.  # noqa: E501
        :type file_format: str
        """
        self.swagger_types = {
            'feed_name': str,
            'input_file_location': str,
            'file_format': str
        }

        self.attribute_map = {
            'feed_name': 'feedName',
            'input_file_location': 'inputFileLocation',
            'file_format': 'fileFormat'
        }
        self._feed_name = feed_name
        self._input_file_location = input_file_location
        self._file_format = file_format

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateRule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateRule of this UpdateRule.  # noqa: E501
        :rtype: UpdateRule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feed_name(self) -> str:
        """Gets the feed_name of this UpdateRule.


        :return: The feed_name of this UpdateRule.
        :rtype: str
        """
        return self._feed_name

    @feed_name.setter
    def feed_name(self, feed_name: str):
        """Sets the feed_name of this UpdateRule.


        :param feed_name: The feed_name of this UpdateRule.
        :type feed_name: str
        """

        self._feed_name = feed_name

    @property
    def input_file_location(self) -> str:
        """Gets the input_file_location of this UpdateRule.


        :return: The input_file_location of this UpdateRule.
        :rtype: str
        """
        return self._input_file_location

    @input_file_location.setter
    def input_file_location(self, input_file_location: str):
        """Sets the input_file_location of this UpdateRule.


        :param input_file_location: The input_file_location of this UpdateRule.
        :type input_file_location: str
        """

        self._input_file_location = input_file_location

    @property
    def file_format(self) -> str:
        """Gets the file_format of this UpdateRule.


        :return: The file_format of this UpdateRule.
        :rtype: str
        """
        return self._file_format

    @file_format.setter
    def file_format(self, file_format: str):
        """Sets the file_format of this UpdateRule.


        :param file_format: The file_format of this UpdateRule.
        :type file_format: str
        """

        self._file_format = file_format
