# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FixedFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, feed_name: str=None, input_file_location: str=None, infer_schema: str=None, dml: str=None):  # noqa: E501
        """FixedFile - a model defined in Swagger

        :param feed_name: The feed_name of this FixedFile.  # noqa: E501
        :type feed_name: str
        :param input_file_location: The input_file_location of this FixedFile.  # noqa: E501
        :type input_file_location: str
        :param infer_schema: The infer_schema of this FixedFile.  # noqa: E501
        :type infer_schema: str
        :param dml: The dml of this FixedFile.  # noqa: E501
        :type dml: str
        """
        self.swagger_types = {
            'feed_name': str,
            'input_file_location': str,
            'infer_schema': str,
            'dml': str
        }

        self.attribute_map = {
            'feed_name': 'feedName',
            'input_file_location': 'inputFileLocation',
            'infer_schema': 'inferSchema',
            'dml': 'dml'
        }

        self._feed_name = feed_name
        self._input_file_location = input_file_location
        self._infer_schema = infer_schema
        self._dml = dml

    @classmethod
    def from_dict(cls, dikt) -> 'FixedFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FixedFile of this FixedFile.  # noqa: E501
        :rtype: FixedFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feed_name(self) -> str:
        """Gets the feed_name of this FixedFile.


        :return: The feed_name of this FixedFile.
        :rtype: str
        """
        return self._feed_name

    @feed_name.setter
    def feed_name(self, feed_name: str):
        """Sets the feed_name of this FixedFile.


        :param feed_name: The feed_name of this FixedFile.
        :type feed_name: str
        """

        self._feed_name = feed_name

    @property
    def input_file_location(self) -> str:
        """Gets the input_file_location of this FixedFile.


        :return: The input_file_location of this FixedFile.
        :rtype: str
        """
        return self._input_file_location

    @input_file_location.setter
    def input_file_location(self, input_file_location: str):
        """Sets the input_file_location of this FixedFile.


        :param input_file_location: The input_file_location of this FixedFile.
        :type input_file_location: str
        """

        self._input_file_location = input_file_location

    @property
    def infer_schema(self) -> str:
        """Gets the infer_schema of this FixedFile.


        :return: The infer_schema of this FixedFile.
        :rtype: str
        """
        return self._infer_schema

    @infer_schema.setter
    def infer_schema(self, infer_schema: str):
        """Sets the infer_schema of this FixedFile.


        :param infer_schema: The infer_schema of this FixedFile.
        :type infer_schema: str
        """

        self._infer_schema = infer_schema

    @property
    def dml(self) -> str:
        """Gets the dml of this FixedFile.


        :return: The dml of this FixedFile.
        :rtype: str
        """
        return self._dml

    @dml.setter
    def dml(self, dml: str):
        """Sets the dml of this FixedFile.


        :param dml: The dml of this FixedFile.
        :type dml: str
        """

        self._dml = dml
